### ISSUE TITLE
move items to other eyedraw website

### ISSUE THREAD

**Issue by biskyt** [AppertaFoundation/openeyes-dev-website#1]
Can the 2 items from this site please be copied into the main appertafoundation/openeyes-website site?

It doesn't make sense having 2 sites, especially as this one only has 2 things in it!

**Comment by pacharanero** [comment]
Yes should be pretty straightforward. Can I just check what is required to be moved here? in the folder `elements/` there is `strabismus` and `strabismusopnote` which I presume are the elements to transfer across. But there are also quite a few other files and folders - I'm not sure if I have the familiarity with the codebase to know what needs to brought across and what can be discarded.

**Comment by biskyt** [comment]
Hi @pacharanero - Yes, I believe it is just a case of merging the contents (including root) of the _elements_ folders together. I note that there are a few files/folders that live on both sites. I would assume that the newest should overwrite the oldest if there are any conflicts

**Comment by biskyt** [comment]
FYI - as much for me as anyone - it looks like the eyedraw code itself can be updated by copying the latest eyedraw.js from the eyedraw repo into scripts/eyedraw.js
